* Memanggil Dataset

In [1]:
import pandas as pd
from kmodes.kmodes import KModes
import numpy as np

In [2]:
DATA_TA=pd.read_csv("DataSkripsi.csv")

In [3]:
DATA_TA

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...  X26  X27  X28  X29  X30  \
0       1   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
1       2   1   1   6   1   2   6   2   1    2  ...    1    2    2    2    2   
2       1   1   1   6   1   1   6   1   1    2  ...    1    2    2    2    2   
3       1   1   1   6   1   1   6   1   1    2  ...    1    2    2    2    2   
4       1   2   4   6   1   1   6   1   2    3  ...    2    2    2    2    2   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
60744   1   3   4   6   1   2   6   2   2    7  ...    2    2    2    2    2   
60745   1   1   1   6   3   2   6   2   1    7  ...    2    2    2    2    2   
60746   1   1   1   6   3   2   6   2   2    7  ...    2    2    2    2    2   
60747   1   1   1   6   1   1   6   1   3    6  ...    1    1    2    2    2   
60748   1   5   4   6   3   2   6   2   2    7  ...    2    2    2    2    2   

       X31  X32  X33  X34  Y  
0        2    1    2    2  5  
1        2    1    2    2  2  
2        2    1    2    1  5  
3        2    1    2    1  5  
4        2    2    2    2  5  
...    ...  ...  ...  ... ..  
60744    2    2    2    2  3  
60745    2    1    2    1  5  
60746    2    1    2    2  3  
60747    2    1    2    1  5  
60748    2    1    2    2  3  

[60749 rows x 35 columns]

In [4]:
print(DATA_TA.dtypes)

X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
X17    int64
X18    int64
X19    int64
X20    int64
X21    int64
X22    int64
X23    int64
X24    int64
X25    int64
X26    int64
X27    int64
X28    int64
X29    int64
X30    int64
X31    int64
X32    int64
X33    int64
X34    int64
Y      int64
dtype: object


* Mengubah type data ke kategorik

In [5]:
DATA_TA[['Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
         'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
         'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
         'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
         'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
         'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan']] =DATA_TA[[
            'Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
             'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
             'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
             'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
             'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
             'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan']].astype('category')

In [5]:
print(DATA_TA.dtypes)

X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
X17    int64
X18    int64
X19    int64
X20    int64
X21    int64
X22    int64
X23    int64
X24    int64
X25    int64
X26    int64
X27    int64
X28    int64
X29    int64
X30    int64
X31    int64
X32    int64
X33    int64
X34    int64
Y      int64
dtype: object


* Mendeteksi data duplikat

In [6]:
duplicate_rows = DATA_TA[DATA_TA.duplicated()]
duplicate_rows

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...  X26  X27  X28  X29  X30  \
20      1   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
24      1   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
54      1   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
91      1   1   1   2   1   1   6   2   2    2  ...    1    2    2    2    2   
97      2   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
60724   1   1   1   6   1   2   6   2   2    7  ...    2    2    2    2    2   
60725   1   1   1   6   3   2   6   2   2    7  ...    1    2    2    2    2   
60731   1   1   1   9   3   2   6   2   1    7  ...    2    2    2    2    2   
60738   1   1   1   6   3   2   6   2   2    7  ...    1    2    2    2    2   
60740   2   1   1   6   3   2   6   2   2    7  ...    1    2    2    2    2   

       X31  X32  X33  X34  Y  
20       2    1    2    2  5  
24       2    1    2    1  5  
54       2    1    2    1  4  
91       2    1    2    1  5  
97       2    1    2    2  3  
...    ...  ...  ...  ... ..  
60724    2    1    2    2  4  
60725    2    1    2    2  5  
60731    2    1    2    1  4  
60738    2    1    2    1  3  
60740    2    1    2    1  3  

[9896 rows x 35 columns]

In [7]:
DATA_TA_CLEAN= DATA_TA.drop_duplicates()
duplicate_rows = DATA_TA_CLEAN[DATA_TA_CLEAN.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X25, X26, X27, X28, X29, X30, X31, X32, X33, X34, Y]
Index: []

[0 rows x 35 columns]

In [8]:
DATA_TA_CLEAN.describe()

X1            X2            X3            X4            X5  \
count  50853.000000  50853.000000  50853.000000  50853.000000  50853.000000   
mean       1.516469      1.506420      2.061275      5.796315      2.381059   
std        0.683368      0.875692      1.347677      1.762886      1.187389   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      6.000000      1.000000   
50%        1.000000      1.000000      1.000000      6.000000      3.000000   
75%        2.000000      2.000000      4.000000      6.000000      3.000000   
max        3.000000      5.000000      4.000000     10.000000      7.000000   

                 X6            X7            X8            X9           X10  \
count  50853.000000  50853.000000  50853.000000  50853.000000  50853.000000   
mean       1.756062      6.078265      1.744283      1.893241      4.112324   
std        0.429460      0.895689      0.436268      0.796331      2.347774   
min        1.000000      1.000000      1.000000      0.000000      1.000000   
25%        2.000000      6.000000      1.000000      1.000000      2.000000   
50%        2.000000      6.000000      2.000000      2.000000      3.000000   
75%        2.000000      6.000000      2.000000      2.000000      6.000000   
max        2.000000     10.000000      2.000000      9.000000     12.000000   

       ...           X26           X27           X28           X29  \
count  ...  50853.000000  50853.000000  50853.000000  50853.000000   
mean   ...      1.381197      1.982617      1.988654      1.991721   
std    ...      0.485686      0.130697      0.105915      0.090611   
min    ...      1.000000      1.000000      1.000000      1.000000   
25%    ...      1.000000      2.000000      2.000000      2.000000   
50%    ...      1.000000      2.000000      2.000000      2.000000   
75%    ...      2.000000      2.000000      2.000000      2.000000   
max    ...      2.000000      2.000000      2.000000      2.000000   

                X30           X31           X32           X33           X34  \
count  50853.000000  50853.000000  50853.000000  50853.000000  50853.000000   
mean       1.987592      1.999095      1.344719      1.980532      1.613356   
std        0.110700      0.030063      0.475281      0.138164      0.486986   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        2.000000      2.000000      1.000000      2.000000      1.000000   
50%        2.000000      2.000000      1.000000      2.000000      2.000000   
75%        2.000000      2.000000      2.000000      2.000000      2.000000   
max        2.000000      2.000000      2.000000      2.000000      2.000000   

                  Y  
count  50853.000000  
mean       3.623916  
std        1.275263  
min        1.000000  
25%        3.000000  
50%        4.000000  
75%        5.000000  
max        5.000000  

[8 rows x 35 columns]

In [9]:
DATA_TA

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...  X26  X27  X28  X29  X30  \
0       1   1   1   2   1   1   6   1   2    2  ...    1    2    2    2    2   
1       2   1   1   6   1   2   6   2   1    2  ...    1    2    2    2    2   
2       1   1   1   6   1   1   6   1   1    2  ...    1    2    2    2    2   
3       1   1   1   6   1   1   6   1   1    2  ...    1    2    2    2    2   
4       1   2   4   6   1   1   6   1   2    3  ...    2    2    2    2    2   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
60744   1   3   4   6   1   2   6   2   2    7  ...    2    2    2    2    2   
60745   1   1   1   6   3   2   6   2   1    7  ...    2    2    2    2    2   
60746   1   1   1   6   3   2   6   2   2    7  ...    2    2    2    2    2   
60747   1   1   1   6   1   1   6   1   3    6  ...    1    1    2    2    2   
60748   1   5   4   6   3   2   6   2   2    7  ...    2    2    2    2    2   

       X31  X32  X33  X34  Y  
0        2    1    2    2  5  
1        2    1    2    2  2  
2        2    1    2    1  5  
3        2    1    2    1  5  
4        2    2    2    2  5  
...    ...  ...  ...  ... ..  
60744    2    2    2    2  3  
60745    2    1    2    1  5  
60746    2    1    2    2  3  
60747    2    1    2    1  5  
60748    2    1    2    2  3  

[60749 rows x 35 columns]

In [11]:
MYDATA=DATA_TA_CLEAN

In [10]:
DATA_TA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60749 entries, 0 to 60748
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      60749 non-null  int64
 1   X2      60749 non-null  int64
 2   X3      60749 non-null  int64
 3   X4      60749 non-null  int64
 4   X5      60749 non-null  int64
 5   X6      60749 non-null  int64
 6   X7      60749 non-null  int64
 7   X8      60749 non-null  int64
 8   X9      60749 non-null  int64
 9   X10     60749 non-null  int64
 10  X11     60749 non-null  int64
 11  X12     60749 non-null  int64
 12  X13     60749 non-null  int64
 13  X14     60749 non-null  int64
 14  X15     60749 non-null  int64
 15  X16     60749 non-null  int64
 16  X17     60749 non-null  int64
 17  X18     60749 non-null  int64
 18  X19     60749 non-null  int64
 19  X20     60749 non-null  int64
 20  X21     60749 non-null  int64
 21  X22     60749 non-null  int64
 22  X23     60749 non-null  int64
 23  X24     607

In [11]:
DATA=DATA_TA[["X1","X15","X10","X13","X4","X14","X19","X11","X16","X5","X26"]]
DATA

X1  X15  X10  X13  X4  X14  X19  X11  X16  X5  X26
0       1    1    2    4   2    3    1    1    1   1    1
1       2    1    2    4   6    3    1    1    1   1    1
2       1    1    2    4   6    9    2    1    1   1    1
3       1    1    2    4   6    2    2    1    1   1    1
4       1    1    3    4   6    3    2    2    1   1    2
...    ..  ...  ...  ...  ..  ...  ...  ...  ...  ..  ...
60744   1    1    7    6   6    8    2    3    3   1    2
60745   1    1    7    4   6    3    2    3    1   3    2
60746   1    1    7    4   6    8    1    3    3   3    2
60747   1    1    6    4   6    3    1    3    1   1    1
60748   1    1    7    5   6    8    2    3    1   3    2

[60749 rows x 11 columns]

In [13]:
#Cluster menggunakan KMODES

In [16]:
km=KModes(n_clusters=5, max_iter=1000, init='random')
clusters=km.fit_predict(DATA)
clusters

array([4, 4, 4, ..., 0, 4, 0], dtype=uint16)

In [17]:
print(km.cluster_centroids_)

[[1 4 7 5 6 8 2 3 4 3 2]
 [2 1 6 5 6 3 2 3 1 3 1]
 [1 1 2 5 6 3 2 1 1 3 2]
 [1 1 2 5 6 3 1 1 1 3 1]
 [1 1 2 4 6 3 1 1 1 1 1]]


In [18]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [19]:
MYDATA["cluster_kmodes"]=cluster_dict
MYDATA

C:\Users\Alharidt\AppData\Local\Temp\ipykernel_792\1961625719.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MYDATA["cluster_kmodes"]=cluster_dict


Kabupaten/Kota Nama Kepala Rumah Tangga   X1  X2  X3  X4  X5  X6  \
0        KOTA BANDA ACEH             WAHYU HIDAYAT   1   1   1   2   1   1   
1        KOTA BANDA ACEH                    MUCHRI   2   1   1   6   1   2   
2        KOTA BANDA ACEH                 USMAN ALI   1   1   1   6   1   1   
3        KOTA BANDA ACEH                    EFENDI   1   1   1   6   1   1   
4        KOTA BANDA ACEH               FARIDAHWATI   1   2   4   6   1   1   
...                  ...                       ...  ..  ..  ..  ..  ..  ..   
60744  KOTA SUBULUSSALAM             DANI SAPUTERA   1   3   4   6   1   2   
60745  KOTA SUBULUSSALAM                  SULASTRI   1   1   1   6   3   2   
60746  KOTA SUBULUSSALAM                     KARDA   1   1   1   6   3   2   
60747  KOTA SUBULUSSALAM                 SUWARSONO   1   1   1   6   1   1   
60748  KOTA SUBULUSSALAM                   PURNOMO   1   5   4   6   3   2   

       X7  X8  ...  X27  X28  X29  X30  X31  X32  X33  X34  Y  cluster_kmodes  
0       6   1  ...    2    2    2    2    2    1    4    2  5               4  
1       6   2  ...    2    2    2    2    2    1    4    2  2               4  
2       6   1  ...    2    2    2    2    2    1    4    1  5               4  
3       6   1  ...    2    2    2    2    2    1    4    1  5               4  
4       6   1  ...    2    2    2    2    2    2    4    2  5               2  
...    ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ... ..             ...  
60744   6   2  ...    2    2    2    2    2    2    4    2  3               0  
60745   6   2  ...    2    2    2    2    2    1    4    1  5               2  
60746   6   2  ...    2    2    2    2    2    1    4    2  3               0  
60747   6   1  ...    1    2    2    2    2    1    4    1  5               4  
60748   6   2  ...    2    2    2    2    2    1    4    2  3               0  

[60744 rows x 38 columns]

In [18]:
MYDATA.to_excel('MYDATA.xlsx', index=False)

In [12]:
import kmedoids

In [13]:
from sklearn.metrics.pairwise import manhattan_distances


In [16]:
from sklearn_extra.cluster import KMedoids
import pandas as pd

In [17]:
# Contoh data
data = pd.DataFrame({
    'X1': [1, 2, 1, 2],
    'X2': [1, 1, 2, 2],
    'X3': [1, 2, 2, 1]
})

In [18]:
data

X1  X2  X3
0   1   1   1
1   2   1   2
2   1   2   2
3   2   2   1

In [26]:

# Inisialisasi KMedoids
kmedoids = KMedoids(n_clusters=5, metric='manhattan', method='pam', random_state=42)

In [27]:
# Fitting model
kmedoids.fit(DATA) 




MemoryError: Unable to allocate 27.5 GiB for an array with shape (60749, 60749) and data type float64

In [24]:
# Hasil clusters
clusters = kmedoids.labels_
print("Clusters:", clusters)


Clusters: [0 1 0 0]


In [25]:

# Medoids
medoids = kmedoids.cluster_centers_
print("Medoids:", medoids)

Medoids: [[1. 1. 1.]
 [2. 1. 2.]]


In [14]:
DATA

X1  X15  X10  X13  X4  X14  X19  X11  X16  X5  X26
0       1    1    2    4   2    3    1    1    1   1    1
1       2    1    2    4   6    3    1    1    1   1    1
2       1    1    2    4   6    9    2    1    1   1    1
3       1    1    2    4   6    2    2    1    1   1    1
4       1    1    3    4   6    3    2    2    1   1    2
...    ..  ...  ...  ...  ..  ...  ...  ...  ...  ..  ...
60744   1    1    7    6   6    8    2    3    3   1    2
60745   1    1    7    4   6    3    2    3    1   3    2
60746   1    1    7    4   6    8    1    3    3   3    2
60747   1    1    6    4   6    3    1    3    1   1    1
60748   1    1    7    5   6    8    2    3    1   3    2

[60749 rows x 11 columns]

In [15]:
diss = manhattan_distances(DATA)

MemoryError: Unable to allocate 27.5 GiB for an array with shape (60749, 60749) and data type float64

In [2]:
import numpy as np # mengimpor modul numpy
diss = np.load('D:/mydata/diss_manhattan.npy') # membaca file npy dan menyimpannya dalam variabel data

MemoryError: Unable to allocate 27.5 GiB for an array with shape (3689833536,) and data type float64

In [22]:
import numpy as np
import random

# Calculate Manhattan distance
def manhattan_distance(point1, point2):
    return np.sum(np.abs(point1 - point2))

# Assign clusters to each data point based on their closest medoid
def assign_clusters(data, medoids):
    num_samples = data.shape[0]
    num_clusters = len(medoids)
    cluster_assignments = np.zeros(num_samples)
    
    for i in range(num_samples):
        distances = []
        for j in range(num_clusters):
            distances.append(manhattan_distance(data[i], medoids[j]))
        cluster_assignments[i] = np.argmin(distances)
    return cluster_assignments

# Calculate new medoids by selecting the data point that has the smallest average Manhattan distance to all other data points in the same cluster
def update_medoids(data, cluster_assignments, num_clusters):
    new_medoids = []
    
    for i in range(num_clusters):
        cluster_points = data[cluster_assignments == i]
        distances = []
        for j in range(cluster_points.shape[0]):
            distances.append(np.sum(np.minimum(manhattan_distance(cluster_points[j], data), manhattan_distance(cluster_points[j], new_medoids)) for data in cluster_points))
        new_medoids.append(cluster_points[np.argmin(distances)])
    return np.array(new_medoids)

# Initialize the k-medoids algorithm
def initialize_medoids(data, num_clusters):
    return random.sample(list(data), num_clusters)

# k-medoids clustering algorithm
def k_medoids(data, num_clusters, num_iterations):
    medoids

In [24]:
kmedoids.fasterpam(diss, 5, max_iter=100, init='random', random_state=None, n_cpu=-1)

KMedoidsResult(loss=896.0, labels=[2 0 4 0 3 0 1 2 0 2 0 3 0 3 3 3 0 2 2 0 2 2 0 0 2 1 2 0 3 3 3 0 1 1 1 0 0
 2 0 0 1 3 0 2 0 2 0 0 4 0 1 2 2 4 2 0 4 0 2 2 2 2 1 2 2 0 2 1 1 0 0 1 2 2
 0 2 3 3 2 4 2 0 3 2 3 2 2 2 0 1 0 2 1 1 0 1 0 1 0 3 1 1 1 0 2 3 2 0 1 2 2
 3 0 2 4 0 4 1 2 2 0 2 2 3 4 2 1 2 0 0 2 2 4 1 2 1 4 2 2 3 2 1 2 4 0 2 3 0
 1 2 2 3 3 2 2 3 2 0 3 0 2 0 1 2 4 2 0 1 2 0 1 0 2 0 3 2 2 2 2 2 0 0 1 0 2
 4 0 2 3 0 2 0 0 3 2 3 1 0 2], medoids=[ 16  71 137 193 114], n_iter=2, n_swaps=19)

In [26]:
diss.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'