* Memanggil Dataset

In [11]:
import pandas as pd
from kmodes.kmodes import KModes
import numpy as np

In [12]:
DATA_TA = pd.read_excel("Data_kmedian.xlsx")

In [13]:
DATA_TA

KOTA Nama Kepala Rumah Tangga (KRT)  \
0        KOTA BANDA ACEH                  WAHYU HIDAYAT   
1        KOTA BANDA ACEH                         MUCHRI   
2        KOTA BANDA ACEH                      USMAN ALI   
3        KOTA BANDA ACEH                         EFENDI   
4        KOTA BANDA ACEH                    FARIDAHWATI   
...                  ...                            ...   
60738  KOTA SUBULUSSALAM                  DANI SAPUTERA   
60739  KOTA SUBULUSSALAM                       SULASTRI   
60740  KOTA SUBULUSSALAM                          KARDA   
60741  KOTA SUBULUSSALAM                      SUWARSONO   
60742  KOTA SUBULUSSALAM                        PURNOMO   

       Jumlah Anggota Rumah Tangga (ART)  Jumlah Keluarga  \
0                                      3                1   
1                                      5                2   
2                                      1                1   
3                                      2                1   
4                                      1                1   
...                                  ...              ...   
60738                                  3                1   
60739                                  1                1   
60740                                  4                1   
60741                                  3                1   
60742                                  3                1   

       Status bangunan tempat tinggal  Status lahan tempat tinggal  \
0                                   1                            1   
1                                   1                            1   
2                                   1                            1   
3                                   1                            1   
4                                   2                            4   
...                               ...                          ...   
60738                               3                            4   
60739                               1                            1   
60740                               1                            1   
60741                               1                            1   
60742                               5                            4   

       Jenis lantai terluas  Jenis dinding terluas  Kondisi dinding  \
0                         2                      1                1   
1                         6                      1                2   
2                         6                      1                1   
3                         6                      1                1   
4                         6                      1                1   
...                     ...                    ...              ...   
60738                     6                      1                2   
60739                     6                      3                2   
60740                     6                      3                2   
60741                     6                      1                1   
60742                     6                      3                2   

       Jenis atap terluas  ...  Mobil  Perahu  Motor tempel  Perahu motor  \
0                       6  ...      2       2             2             2   
1                       6  ...      2       2             2             2   
2                       6  ...      2       2             2             2   
3                       6  ...      2       2             2             2   
4                       6  ...      2       2             2             2   
...                   ...  ...    ...     ...           ...           ...   
60738                   6  ...      2       2             2             2   
60739                   6  ...      2       2             2             2   
60740                   6  ...      2       2             2             2   
60741                   6  ...      1       2             2             2   
60742                   6  ...      2

In [16]:
print(DATA_TA.dtypes)

KOTA                                  object
Nama Kepala Rumah Tangga (KRT)        object
Jumlah Anggota Rumah Tangga (ART)      int64
Jumlah Keluarga                        int64
Status bangunan tempat tinggal         int64
Status lahan tempat tinggal            int64
Jenis lantai terluas                   int64
Jenis dinding terluas                  int64
Kondisi dinding                        int64
Jenis atap terluas                     int64
Kondisi atap                           int64
Jumlah kamar tidur                     int64
Sumber air minum                       int64
Cara memperoleh air minum              int64
Sumber penerangan utama                int64
Daya listrik terpasang                 int64
Bahan bakar untuk memasak              int64
Penggunaan fasilitas BAB               int64
Jenis kloset                           int64
Tempat pembuangan akhir tinja          int64
Tabung gas 5,5kg atau lebih            int64
Lemari es/kulkas                       int64
AC        

* Mengubah type data ke kategorik

In [5]:
DATA_TA[['Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
         'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
         'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
         'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
         'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
         'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan',"cluster_kmedian"]] =DATA_TA[[
            'Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
             'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
             'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
             'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
             'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
             'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan',"cluster_kmedian"]].astype('category')

In [6]:
print(DATA_TA.dtypes)

KOTA                                    object
Nama Kepala Rumah Tangga (KRT)          object
Jumlah Anggota Rumah Tangga (ART)     category
Jumlah Keluarga                       category
Status bangunan tempat tinggal        category
Status lahan tempat tinggal           category
Jenis lantai terluas                  category
Jenis dinding terluas                 category
Kondisi dinding                       category
Jenis atap terluas                    category
Kondisi atap                          category
Jumlah kamar tidur                    category
Sumber air minum                      category
Cara memperoleh air minum             category
Sumber penerangan utama               category
Daya listrik terpasang                category
Bahan bakar untuk memasak             category
Penggunaan fasilitas BAB              category
Jenis kloset                          category
Tempat pembuangan akhir tinja         category
Tabung gas 5,5kg atau lebih           category
Lemari es/kul

* Mendeteksi data duplikat

In [18]:
duplicate_rows = DATA_TA[DATA_TA.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [KOTA, Nama Kepala Rumah Tangga (KRT), Jumlah Anggota Rumah Tangga (ART), Jumlah Keluarga, Status bangunan tempat tinggal, Status lahan tempat tinggal, Jenis lantai terluas, Jenis dinding terluas, Kondisi dinding, Jenis atap terluas, Kondisi atap, Jumlah kamar tidur, Sumber air minum, Cara memperoleh air minum, Sumber penerangan utama, Daya listrik terpasang, Bahan bakar untuk memasak, Penggunaan fasilitas BAB, Jenis kloset, Tempat pembuangan akhir tinja, Tabung gas 5,5kg atau lebih, Lemari es/kulkas, AC, Pemanas air, Televisi, Emas/perhiasan/tabungan, Komputer, Sepeda, Sepeda motor, Mobil, Perahu, Motor tempel, Perahu motor, Kapal, Aset lahan, Rumah di tempat lain, ART memiliki usaha sendiri/bersama, Status Kesejahteraan, cluster_kmedian]
Index: []

[0 rows x 39 columns]

In [19]:
DATA_TA_CLEAN= DATA_TA.drop_duplicates()
duplicate_rows = DATA_TA_CLEAN[DATA_TA_CLEAN.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [KOTA, Nama Kepala Rumah Tangga (KRT), Jumlah Anggota Rumah Tangga (ART), Jumlah Keluarga, Status bangunan tempat tinggal, Status lahan tempat tinggal, Jenis lantai terluas, Jenis dinding terluas, Kondisi dinding, Jenis atap terluas, Kondisi atap, Jumlah kamar tidur, Sumber air minum, Cara memperoleh air minum, Sumber penerangan utama, Daya listrik terpasang, Bahan bakar untuk memasak, Penggunaan fasilitas BAB, Jenis kloset, Tempat pembuangan akhir tinja, Tabung gas 5,5kg atau lebih, Lemari es/kulkas, AC, Pemanas air, Televisi, Emas/perhiasan/tabungan, Komputer, Sepeda, Sepeda motor, Mobil, Perahu, Motor tempel, Perahu motor, Kapal, Aset lahan, Rumah di tempat lain, ART memiliki usaha sendiri/bersama, Status Kesejahteraan, cluster_kmedian]
Index: []

[0 rows x 39 columns]

In [9]:
DATA_TA_CLEAN.describe()

KOTA Nama Kepala Rumah Tangga (KRT)  \
count         60743                          60743   
unique            5                          32865   
top     KOTA LANGSA                       ZULKIFLI   
freq          17875                            228   

        Jumlah Anggota Rumah Tangga (ART)  Jumlah Keluarga  \
count                               60743            60743   
unique                                 14                3   
top                                     4                1   
freq                                13752            36848   

        Status bangunan tempat tinggal  Status lahan tempat tinggal  \
count                            60743                        60743   
unique                               5                            4   
top                                  1                            1   
freq                             44390                        37188   

        Jenis lantai terluas  Jenis dinding terluas  Kondisi dinding  \
count                  60743                  60743            60743   
unique                    10                      7                2   
top                        6                      3                2   
freq                   41207                  36429            46180   

        Jenis atap terluas  ...  Mobil  Perahu  Motor tempel  Perahu motor  \
count                60743  ...  60743   60743         60743         60743   
unique                  10  ...      2       2             2             2   
top                      6  ...      2       2             2             2   
freq                 54275  ...  59844   60142         60318         60102   

        Kapal  Aset lahan  Rumah di tempat lain  \
count   60743       60743                 60743   
unique      2           2                     2   
top         2           1                     2   
freq    60697       41028                 59749   

        ART memiliki usaha sendiri/bersama  Status Kesejahteraan  \
count                                60743                 60743   
unique                                   2                     5   
top                                      2                     5   
freq                                 38183                 21126   

        cluster_kmedian  
count             60743  
unique                5  
top                   4  
freq              14499  

[4 rows x 39 columns]

In [10]:
DATA_TA_CLEAN

KOTA Nama Kepala Rumah Tangga (KRT)  \
0        KOTA BANDA ACEH                  WAHYU HIDAYAT   
1        KOTA BANDA ACEH                         MUCHRI   
2        KOTA BANDA ACEH                      USMAN ALI   
3        KOTA BANDA ACEH                         EFENDI   
4        KOTA BANDA ACEH                    FARIDAHWATI   
...                  ...                            ...   
60738  KOTA SUBULUSSALAM                  DANI SAPUTERA   
60739  KOTA SUBULUSSALAM                       SULASTRI   
60740  KOTA SUBULUSSALAM                          KARDA   
60741  KOTA SUBULUSSALAM                      SUWARSONO   
60742  KOTA SUBULUSSALAM                        PURNOMO   

      Jumlah Anggota Rumah Tangga (ART) Jumlah Keluarga  \
0                                     3               1   
1                                     5               2   
2                                     1               1   
3                                     2               1   
4                                     1               1   
...                                 ...             ...   
60738                                 3               1   
60739                                 1               1   
60740                                 4               1   
60741                                 3               1   
60742                                 3               1   

      Status bangunan tempat tinggal Status lahan tempat tinggal  \
0                                  1                           1   
1                                  1                           1   
2                                  1                           1   
3                                  1                           1   
4                                  2                           4   
...                              ...                         ...   
60738                              3                           4   
60739                              1                           1   
60740                              1                           1   
60741                              1                           1   
60742                              5                           4   

      Jenis lantai terluas Jenis dinding terluas Kondisi dinding  \
0                        2                     1               1   
1                        6                     1               2   
2                        6                     1               1   
3                        6                     1               1   
4                        6                     1               1   
...                    ...                   ...             ...   
60738                    6                     1               2   
60739                    6                     3               2   
60740                    6                     3               2   
60741                    6                     1               1   
60742                    6                     3               2   

      Jenis atap terluas  ... Mobil Perahu Motor tempel Perahu motor Kapal  \
0                      6  ...     2      2            2            2     2   
1                      6  ...     2      2            2            2     2   
2                      6  ...     2      2            2            2     2   
3                      6  ...     2      2            2            2     2   
4                      6  ...     2      2            2            2     2   
...                  ...  ...   ...    ...          ...          ...   ...   
60738                  6  ...     2      2            2            2     2   
60739                  6  ...     2      2            2            2     2   
60740                  6  ...     2      2            2            2     2   
60741                  6  ...     1      2            2            2     2   
60742                  6  ...     2      2            2            2     2   

      Aset lahan Rumah di tempa

In [20]:
MYDATA=DATA_TA_CLEAN

In [21]:
DATA=DATA_TA_CLEAN.drop(["KOTA","Nama Kepala Rumah Tangga (KRT)","Status Kesejahteraan","cluster_kmedian"], axis=1)
DATA

Jumlah Anggota Rumah Tangga (ART)  Jumlah Keluarga  \
0                                      3                1   
1                                      5                2   
2                                      1                1   
3                                      2                1   
4                                      1                1   
...                                  ...              ...   
60738                                  3                1   
60739                                  1                1   
60740                                  4                1   
60741                                  3                1   
60742                                  3                1   

       Status bangunan tempat tinggal  Status lahan tempat tinggal  \
0                                   1                            1   
1                                   1                            1   
2                                   1                            1   
3                                   1                            1   
4                                   2                            4   
...                               ...                          ...   
60738                               3                            4   
60739                               1                            1   
60740                               1                            1   
60741                               1                            1   
60742                               5                            4   

       Jenis lantai terluas  Jenis dinding terluas  Kondisi dinding  \
0                         2                      1                1   
1                         6                      1                2   
2                         6                      1                1   
3                         6                      1                1   
4                         6                      1                1   
...                     ...                    ...              ...   
60738                     6                      1                2   
60739                     6                      3                2   
60740                     6                      3                2   
60741                     6                      1                1   
60742                     6                      3                2   

       Jenis atap terluas  Kondisi atap  Jumlah kamar tidur  ...  Sepeda  \
0                       6             1                   2  ...       2   
1                       6             2                   1  ...       1   
2                       6             1                   1  ...       2   
3                       6             1                   1  ...       2   
4                       6             1                   2  ...       2   
...                   ...           ...                 ...  ...     ...   
60738                   6             2                   2  ...       2   
60739                   6             2                   1  ...       2   
60740                   6             2                   2  ...       2   
60741                   6             1                   2  ...       2   
60742                   6             2                   2  ...       2   

       Sepeda motor  Mobil  Perahu  Motor tempel  Perahu motor  Kapal  \
0                 1      2       2             2             2      2   
1                 1      2       2             2             2      2   
2                 1      2       2             2             2      2   
3                 1      2       2             2             2      2   
4                 2      2       2             2             2      2   
...             ...    ...     ...           ...           ...    ...   
60738             2      2       2             2             2      2   
60739             2      2       2             2             2      2   
60740     

In [13]:
#Cluster menggunakan KMODES

In [14]:
km=KModes(n_clusters=5, max_iter=1000, init='random')
clusters=km.fit_predict(DATA)
clusters

array([0, 1, 0, ..., 4, 0, 4], dtype=uint16)

In [15]:
print(km.cluster_centroids_)

[[4 1 1 1 6 1 1 6 1 2 2 1 1 4 3 1 1 1 2 1 2 2 1 2 2 2 1 2 2 2 2 2 1 2 2]
 [5 2 1 1 6 3 2 6 2 2 2 1 1 5 3 1 1 1 2 1 2 2 1 2 2 2 1 2 2 2 2 2 1 2 2]
 [3 1 3 4 6 3 2 6 2 1 2 1 1 5 3 1 1 1 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2]
 [1 1 1 1 6 3 2 6 2 1 7 3 1 5 8 4 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2]
 [4 1 1 1 6 3 2 6 2 2 6 3 1 5 3 1 1 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 2]]


In [16]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [17]:
MYDATA["cluster_kmodes"]=cluster_dict
MYDATA

KOTA Nama Kepala Rumah Tangga (KRT)  \
0        KOTA BANDA ACEH                  WAHYU HIDAYAT   
1        KOTA BANDA ACEH                         MUCHRI   
2        KOTA BANDA ACEH                      USMAN ALI   
3        KOTA BANDA ACEH                         EFENDI   
4        KOTA BANDA ACEH                    FARIDAHWATI   
...                  ...                            ...   
60738  KOTA SUBULUSSALAM                  DANI SAPUTERA   
60739  KOTA SUBULUSSALAM                       SULASTRI   
60740  KOTA SUBULUSSALAM                          KARDA   
60741  KOTA SUBULUSSALAM                      SUWARSONO   
60742  KOTA SUBULUSSALAM                        PURNOMO   

      Jumlah Anggota Rumah Tangga (ART) Jumlah Keluarga  \
0                                     3               1   
1                                     5               2   
2                                     1               1   
3                                     2               1   
4                                     1               1   
...                                 ...             ...   
60738                                 3               1   
60739                                 1               1   
60740                                 4               1   
60741                                 3               1   
60742                                 3               1   

      Status bangunan tempat tinggal Status lahan tempat tinggal  \
0                                  1                           1   
1                                  1                           1   
2                                  1                           1   
3                                  1                           1   
4                                  2                           4   
...                              ...                         ...   
60738                              3                           4   
60739                              1                           1   
60740                              1                           1   
60741                              1                           1   
60742                              5                           4   

      Jenis lantai terluas Jenis dinding terluas Kondisi dinding  \
0                        2                     1               1   
1                        6                     1               2   
2                        6                     1               1   
3                        6                     1               1   
4                        6                     1               1   
...                    ...                   ...             ...   
60738                    6                     1               2   
60739                    6                     3               2   
60740                    6                     3               2   
60741                    6                     1               1   
60742                    6                     3               2   

      Jenis atap terluas  ... Perahu Motor tempel Perahu motor Kapal  \
0                      6  ...      2            2            2     2   
1                      6  ...      2            2            2     2   
2                      6  ...      2            2            2     2   
3                      6  ...      2            2            2     2   
4                      6  ...      2            2            2     2   
...                  ...  ...    ...          ...          ...   ...   
60738                  6  ...      2            2            2     2   
60739                  6  ...      2            2            2     2   
60740                  6  ...      2            2            2     2   
60741                  6  ...      2            2            2     2   
60742                  6  ...      2            2            2     2   

      Aset lahan Rumah di tempat lain ART memiliki usaha sendiri/bersama  \
0              1           

In [18]:
MYDATA.to_excel('MYDATA.xlsx', index=False)

In [7]:
import kmedoids

In [8]:
classsklearn_extra.cluster.KMedoids(n_clusters=8, metric='euclidean', method='alternate', init='heuristic', max_iter=300, random_state=None

SyntaxError: incomplete input (1555283449.py, line 1)

In [9]:
import numpy as np
import random

# Calculate Manhattan distance
def manhattan_distance(point1, point2):
    return np.sum(np.abs(point1 - point2))

# Assign clusters to each data point based on their closest medoid
def assign_clusters(data, medoids):
    num_samples = data.shape[0]
    num_clusters = len(medoids)
    cluster_assignments = np.zeros(num_samples)
    
    for i in range(num_samples):
        distances = []
        for j in range(num_clusters):
            distances.append(manhattan_distance(data[i], medoids[j]))
        cluster_assignments[i] = np.argmin(distances)
    return cluster_assignments

# Calculate new medoids by selecting the data point that has the smallest average Manhattan distance to all other data points in the same cluster
def update_medoids(data, cluster_assignments, num_clusters):
    new_medoids = []
    
    for i in range(num_clusters):
        cluster_points = data[cluster_assignments == i]
        distances = []
        for j in range(cluster_points.shape[0]):
            distances.append(np.sum(np.minimum(manhattan_distance(cluster_points[j], data), manhattan_distance(cluster_points[j], new_medoids)) for data in cluster_points))
        new_medoids.append(cluster_points[np.argmin(distances)])
    return np.array(new_medoids)

# Initialize the k-medoids algorithm
def initialize_medoids(data, num_clusters):
    return random.sample(list(data), num_clusters)

# k-medoids clustering algorithm
def k_medoids(data, num_clusters, num_iterations):
    medoids

In [38]:
class sklearn_extra.cluster.KMedoids(n_clusters=8, metric='euclidean', method='alternate', init='heuristic', max_iter=300, random_state=None)

SyntaxError: invalid syntax (3074810529.py, line 1)

In [39]:
from sklearn.cluster import KMedoids
import numpy as np
KMedoids(n_clusters=5, metric='manhattan', method='pam',init='random', max_iter=100, random_state=none).fit(DATA)

ImportError: cannot import name 'KMedoids' from 'sklearn.cluster' (C:\Users\Alharidt\AppData\Roaming\Python\Python311\site-packages\sklearn\cluster\__init__.py)

Defaulting to user installation because normal site-packages is not writeable


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: celery 5.0.5 has a non-standard dependency specifier pytz>dev. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
