* Memanggil Dataset

In [1]:
import pandas as pd
from kmodes.kmodes import KModes
import numpy as np

In [2]:
DATA_TA=pd.read_csv("testing.csv")

In [3]:
DATA_TA

Status.kesejahteraan  Jumlah.Anggota.rumah.tangga  Jumlah.keluarga  \
0                          2                            3                1   
1                          4                            2                1   
2                          1                            4                1   
3                          2                            6                2   
4                          3                            2                1   
...                      ...                          ...              ...   
286710                     3                            2                1   
286711                     3                            3                1   
286712                     3                            4                1   
286713                     1                            7                3   
286714                     3                            5                2   

        Status.bangunan.tempat.tinggal  Status.lahan.tempat.tinggal  \
0                                    1                            1   
1                                    1                            1   
2                                    1                            1   
3                                    1                            1   
4                                    1                            1   
...                                ...                          ...   
286710                               1                            1   
286711                               1                            1   
286712                               1                            1   
286713                               1                            1   
286714                               1                            1   

        Jenis.lantai.terluas  Jenis.dinding.terluas  Kondisi.dinding  \
0                          6                      1                2   
1                          6                      1                2   
2                          6                      1                2   
3                          6                      1                1   
4                          9                      1                2   
...                      ...                    ...              ...   
286710                     6                      3                2   
286711                     6                      3                2   
286712                     2                      1                2   
286713                     8                      3                2   
286714                     2                      1                2   

        Jenis.atap.terluas  Kondisi.atap  ...  Sepeda  Sepeda.motor  Mobil  \
0                        6             1  ...       1             2      2   
1                        6             2  ...       2             1      2   
2                        6             2  ...       2             1      2   
3                        6             2  ...       2             1      2   
4                        6             2  ...       1             2      2   
...                    ...           ...  ...     ...           ...    ...   
286710                   6             2  ...       2             2      2   
286711                   6             2  ...       2             2      2   
286712                   6             2  ...       1             1      2   
286713                   9             2  ...       2             2      2   
286714                   6             2  ...       1             1      2   

        Perahu  Motor.tempel  Perahu.motor  Kapal  Aset.lahan  \
0            2             2             2      2           1   
1            2             2             2      2           1   
2            2             2             2      2           1   
3            2             2             2      2           1   
4            2             2             2      2           1   
...        ...           .

In [6]:
print(DATA_TA.dtypes)

Kabupaten/Kota               object
Nama Kepala Rumah Tangga     object
X1                            int64
X2                            int64
X3                            int64
X4                            int64
X5                            int64
X6                            int64
X7                            int64
X8                            int64
X9                            int64
X10                           int64
X11                           int64
X12                           int64
X13                           int64
X14                           int64
X15                           int64
X16                           int64
X17                           int64
X18                           int64
X19                           int64
X20                           int64
X21                           int64
X22                           int64
X23                           int64
X24                           int64
X25                           int64
X26                         

* Mengubah type data ke kategorik

In [5]:
DATA_TA[['Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
         'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
         'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
         'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
         'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
         'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan']] =DATA_TA[[
            'Jumlah Anggota Rumah Tangga (ART)','Jumlah Keluarga','Status bangunan tempat tinggal','Status lahan tempat tinggal','Jenis lantai terluas',
             'Jenis dinding terluas','Kondisi dinding','Jenis atap terluas','Kondisi atap','Jumlah kamar tidur','Sumber air minum',
             'Cara memperoleh air minum','Sumber penerangan utama','Daya listrik terpasang','Bahan bakar untuk memasak',
             'Penggunaan fasilitas BAB','Jenis kloset','Tempat pembuangan akhir tinja','Tabung gas 5,5kg atau lebih','Lemari es/kulkas',
             'AC','Pemanas air','Televisi','Emas/perhiasan/tabungan','Komputer','Sepeda','Sepeda motor','Mobil','Perahu','Motor tempel',
             'Perahu motor','Kapal','Aset lahan','Rumah di tempat lain','ART memiliki usaha sendiri/bersama','Status Kesejahteraan']].astype('category')

In [6]:
print(DATA_TA.dtypes)

KOTA                                    object
Nama Kepala Rumah Tangga (KRT)          object
Jumlah Anggota Rumah Tangga (ART)     category
Jumlah Keluarga                       category
Status bangunan tempat tinggal        category
Status lahan tempat tinggal           category
Jenis lantai terluas                  category
Jenis dinding terluas                 category
Kondisi dinding                       category
Jenis atap terluas                    category
Kondisi atap                          category
Jumlah kamar tidur                    category
Sumber air minum                      category
Cara memperoleh air minum             category
Sumber penerangan utama               category
Daya listrik terpasang                category
Bahan bakar untuk memasak             category
Penggunaan fasilitas BAB              category
Jenis kloset                          category
Tempat pembuangan akhir tinja         category
Tabung gas 5,5kg atau lebih           category
Lemari es/kul

* Mendeteksi data duplikat

In [7]:
duplicate_rows = DATA_TA[DATA_TA.duplicated()]
duplicate_rows

Kabupaten/Kota Nama Kepala Rumah Tangga   X1  X2  X3  X4  X5  X6  X7  \
9377    KOTA BANDA ACEH                JAFARUDDIN   1   1   1   6   1   1   6   
24106       KOTA LANGSA                   NURAINI   1   1   1   6   3   2   6   
26592       KOTA LANGSA                  ISKANDAR   1   1   1   6   3   2   6   
39416  KOTA LHOKSEUMAWE                  RASYIDAH   1   1   1   6   1   2   6   
39756  KOTA LHOKSEUMAWE                   MULYADI   1   2   4   6   3   2   6   

       X8  ...  X26  X27  X28  X29  X30  X31  X32  X33  X34  Y  
9377    1  ...    1    2    2    2    2    2    1    4    2  2  
24106   2  ...    1    2    2    2    2    2    1    4    2  5  
26592   2  ...    1    2    2    2    2    2    1    4    1  5  
39416   2  ...    2    2    2    2    2    2    1    4    2  5  
39756   2  ...    1    2    2    2    2    2    2    4    1  5  

[5 rows x 37 columns]

In [4]:
DATA_TA_CLEAN= DATA_TA.drop_duplicates()
duplicate_rows = DATA_TA_CLEAN[DATA_TA_CLEAN.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [Status.kesejahteraan, Jumlah.Anggota.rumah.tangga, Jumlah.keluarga, Status.bangunan.tempat.tinggal, Status.lahan.tempat.tinggal, Jenis.lantai.terluas, Jenis.dinding.terluas, Kondisi.dinding, Jenis.atap.terluas, Kondisi.atap, Jumlah.kamar.tidur, Sumber.air.minum, Cara.memperoleh.air.minum, Sumber.penerangan.utama, Daya.listrik.terpasang, Bahan.bakar.untuk.memasak, Penggunaan.fasilitas.BAB, Jenis.kloset, Tempat.pembuangan.akhir.tinja, Tabung.gas.5.5kg.atau.lebih, Lemari.es.kulkas, AC, Pemanas.air, Televisi, Emas.perhiasan.tabungan, Komputer, Sepeda, Sepeda.motor, Mobil, Perahu, Motor.tempel, Perahu.motor, Kapal, Aset.lahan, Rumah.di.tempat.lain, ART.memiliki.usaha.sendiri.bersama]
Index: []

[0 rows x 36 columns]

In [9]:
DATA_TA_CLEAN.describe()

X1            X2            X3            X4            X5  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.492542      1.471503      1.990682      5.774183      2.364662   
std        0.669497      0.849359      1.332241      1.717152      1.159472   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      6.000000      1.000000   
50%        1.000000      1.000000      1.000000      6.000000      3.000000   
75%        2.000000      2.000000      4.000000      6.000000      3.000000   
max        3.000000      5.000000      4.000000     10.000000      7.000000   

                 X6            X7            X8            X9           X10  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.760273      6.064204      1.751366      1.894475      4.033748   
std        0.426921      0.830969      0.432224      0.761282      2.340832   
min        1.000000      1.000000      1.000000      0.000000      1.000000   
25%        2.000000      6.000000      2.000000      1.000000      2.000000   
50%        2.000000      6.000000      2.000000      2.000000      3.000000   
75%        2.000000      6.000000      2.000000      2.000000      6.000000   
max        2.000000     10.000000      2.000000      9.000000     12.000000   

       ...           X26           X27           X28           X29  \
count  ...  60744.000000  60744.000000  60744.000000  60744.000000   
mean   ...      1.375280      1.985200      1.990106      1.993003   
std    ...      0.484199      0.120752      0.098976      0.083353   
min    ...      1.000000      1.000000      1.000000      1.000000   
25%    ...      1.000000      2.000000      2.000000      2.000000   
50%    ...      1.000000      2.000000      2.000000      2.000000   
75%    ...      2.000000      2.000000      2.000000      2.000000   
max    ...      2.000000      2.000000      2.000000      2.000000   

                X30           X31           X32           X33           X34  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.989448      1.999243      1.324542      3.766825      1.628605   
std        0.102183      0.027508      0.468207      0.631858      0.483182   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        2.000000      2.000000      1.000000      4.000000      1.000000   
50%        2.000000      2.000000      1.000000      4.000000      2.000000   
75%        2.000000      2.000000      2.000000      4.000000      2.000000   
max        2.000000      2.000000      2.000000      4.000000      2.000000   

                  Y  
count  60744.000000  
mean       3.670206  
std        1.254295  
min        1.000000  
25%        3.000000  
50%        4.000000  
75%        5.000000  
max        5.000000  

[8 rows x 35 columns]

In [5]:
DATA_TA_CLEAN

Status.kesejahteraan  Jumlah.Anggota.rumah.tangga  Jumlah.keluarga  \
0                          2                            3                1   
1                          4                            2                1   
2                          1                            4                1   
3                          2                            6                2   
4                          3                            2                1   
...                      ...                          ...              ...   
286708                     2                            4                1   
286709                     4                            5                2   
286710                     3                            2                1   
286711                     3                            3                1   
286712                     3                            4                1   

        Status.bangunan.tempat.tinggal  Status.lahan.tempat.tinggal  \
0                                    1                            1   
1                                    1                            1   
2                                    1                            1   
3                                    1                            1   
4                                    1                            1   
...                                ...                          ...   
286708                               1                            1   
286709                               1                            1   
286710                               1                            1   
286711                               1                            1   
286712                               1                            1   

        Jenis.lantai.terluas  Jenis.dinding.terluas  Kondisi.dinding  \
0                          6                      1                2   
1                          6                      1                2   
2                          6                      1                2   
3                          6                      1                1   
4                          9                      1                2   
...                      ...                    ...              ...   
286708                     6                      3                2   
286709                     6                      3                2   
286710                     6                      3                2   
286711                     6                      3                2   
286712                     2                      1                2   

        Jenis.atap.terluas  Kondisi.atap  ...  Sepeda  Sepeda.motor  Mobil  \
0                        6             1  ...       1             2      2   
1                        6             2  ...       2             1      2   
2                        6             2  ...       2             1      2   
3                        6             2  ...       2             1      2   
4                        6             2  ...       1             2      2   
...                    ...           ...  ...     ...           ...    ...   
286708                   9             2  ...       1             2      2   
286709                   6             2  ...       2             2      2   
286710                   6             2  ...       2             2      2   
286711                   6             2  ...       2             2      2   
286712                   6             2  ...       1             1      2   

        Perahu  Motor.tempel  Perahu.motor  Kapal  Aset.lahan  \
0            2             2             2      2           1   
1            2             2             2      2           1   
2            2             2             2      2           1   
3            2             2             2      2           1   
4            2             2             2      2           1   
...        ...           .

In [11]:
MYDATA=DATA_TA_CLEAN

In [12]:
DATA_TA_CLEAN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60744 entries, 0 to 60748
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Kabupaten/Kota             60744 non-null  object
 1   Nama Kepala Rumah Tangga   60744 non-null  object
 2   X1                         60744 non-null  int64 
 3   X2                         60744 non-null  int64 
 4   X3                         60744 non-null  int64 
 5   X4                         60744 non-null  int64 
 6   X5                         60744 non-null  int64 
 7   X6                         60744 non-null  int64 
 8   X7                         60744 non-null  int64 
 9   X8                         60744 non-null  int64 
 10  X9                         60744 non-null  int64 
 11  X10                        60744 non-null  int64 
 12  X11                        60744 non-null  int64 
 13  X12                        60744 non-null  int64 
 14  X13        

In [15]:
DATA=DATA_TA_CLEAN[["X1","X15","X10","X13","X4","X14","X19","X11","X16","X5","X26"]]
DATA

X1  X15  X10  X13  X4  X14  X19  X11  X16  X5  X26
0       1    1    2    4   2    3    1    1    1   1    1
1       2    1    2    4   6    3    1    1    1   1    1
2       1    1    2    4   6    9    2    1    1   1    1
3       1    1    2    4   6    2    2    1    1   1    1
4       1    1    3    4   6    3    2    2    1   1    2
...    ..  ...  ...  ...  ..  ...  ...  ...  ...  ..  ...
60744   1    1    7    6   6    8    2    3    3   1    2
60745   1    1    7    4   6    3    2    3    1   3    2
60746   1    1    7    4   6    8    1    3    3   3    2
60747   1    1    6    4   6    3    1    3    1   1    1
60748   1    1    7    5   6    8    2    3    1   3    2

[60744 rows x 11 columns]

In [13]:
#Cluster menggunakan KMODES

In [16]:
km=KModes(n_clusters=5, max_iter=1000, init='random')
clusters=km.fit_predict(DATA)
clusters

array([4, 4, 4, ..., 0, 4, 0], dtype=uint16)

In [17]:
print(km.cluster_centroids_)

[[1 4 7 5 6 8 2 3 4 3 2]
 [2 1 6 5 6 3 2 3 1 3 1]
 [1 1 2 5 6 3 2 1 1 3 2]
 [1 1 2 5 6 3 1 1 1 3 1]
 [1 1 2 4 6 3 1 1 1 1 1]]


In [18]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [19]:
MYDATA["cluster_kmodes"]=cluster_dict
MYDATA

C:\Users\Alharidt\AppData\Local\Temp\ipykernel_792\1961625719.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MYDATA["cluster_kmodes"]=cluster_dict


Kabupaten/Kota Nama Kepala Rumah Tangga   X1  X2  X3  X4  X5  X6  \
0        KOTA BANDA ACEH             WAHYU HIDAYAT   1   1   1   2   1   1   
1        KOTA BANDA ACEH                    MUCHRI   2   1   1   6   1   2   
2        KOTA BANDA ACEH                 USMAN ALI   1   1   1   6   1   1   
3        KOTA BANDA ACEH                    EFENDI   1   1   1   6   1   1   
4        KOTA BANDA ACEH               FARIDAHWATI   1   2   4   6   1   1   
...                  ...                       ...  ..  ..  ..  ..  ..  ..   
60744  KOTA SUBULUSSALAM             DANI SAPUTERA   1   3   4   6   1   2   
60745  KOTA SUBULUSSALAM                  SULASTRI   1   1   1   6   3   2   
60746  KOTA SUBULUSSALAM                     KARDA   1   1   1   6   3   2   
60747  KOTA SUBULUSSALAM                 SUWARSONO   1   1   1   6   1   1   
60748  KOTA SUBULUSSALAM                   PURNOMO   1   5   4   6   3   2   

       X7  X8  ...  X27  X28  X29  X30  X31  X32  X33  X34  Y  cluster_kmodes  
0       6   1  ...    2    2    2    2    2    1    4    2  5               4  
1       6   2  ...    2    2    2    2    2    1    4    2  2               4  
2       6   1  ...    2    2    2    2    2    1    4    1  5               4  
3       6   1  ...    2    2    2    2    2    1    4    1  5               4  
4       6   1  ...    2    2    2    2    2    2    4    2  5               2  
...    ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ... ..             ...  
60744   6   2  ...    2    2    2    2    2    2    4    2  3               0  
60745   6   2  ...    2    2    2    2    2    1    4    1  5               2  
60746   6   2  ...    2    2    2    2    2    1    4    2  3               0  
60747   6   1  ...    1    2    2    2    2    1    4    1  5               4  
60748   6   2  ...    2    2    2    2    2    1    4    2  3               0  

[60744 rows x 38 columns]

In [18]:
MYDATA.to_excel('MYDATA.xlsx', index=False)

In [19]:
import kmedoids

In [7]:
from sklearn.metrics.pairwise import manhattan_distances


In [21]:
sampel=pd.read_excel("sampel2.xlsx")

In [8]:
diss = manhattan_distances(DATA_TA_CLEAN)

MemoryError: Unable to allocate 429. GiB for an array with shape (239818, 239818) and data type float64

In [2]:
import numpy as np # mengimpor modul numpy
diss = np.load('D:/mydata/diss_manhattan.npy') # membaca file npy dan menyimpannya dalam variabel data

MemoryError: Unable to allocate 27.5 GiB for an array with shape (3689833536,) and data type float64

In [22]:
import numpy as np
import random

# Calculate Manhattan distance
def manhattan_distance(point1, point2):
    return np.sum(np.abs(point1 - point2))

# Assign clusters to each data point based on their closest medoid
def assign_clusters(data, medoids):
    num_samples = data.shape[0]
    num_clusters = len(medoids)
    cluster_assignments = np.zeros(num_samples)
    
    for i in range(num_samples):
        distances = []
        for j in range(num_clusters):
            distances.append(manhattan_distance(data[i], medoids[j]))
        cluster_assignments[i] = np.argmin(distances)
    return cluster_assignments

# Calculate new medoids by selecting the data point that has the smallest average Manhattan distance to all other data points in the same cluster
def update_medoids(data, cluster_assignments, num_clusters):
    new_medoids = []
    
    for i in range(num_clusters):
        cluster_points = data[cluster_assignments == i]
        distances = []
        for j in range(cluster_points.shape[0]):
            distances.append(np.sum(np.minimum(manhattan_distance(cluster_points[j], data), manhattan_distance(cluster_points[j], new_medoids)) for data in cluster_points))
        new_medoids.append(cluster_points[np.argmin(distances)])
    return np.array(new_medoids)

# Initialize the k-medoids algorithm
def initialize_medoids(data, num_clusters):
    return random.sample(list(data), num_clusters)

# k-medoids clustering algorithm
def k_medoids(data, num_clusters, num_iterations):
    medoids

In [24]:
kmedoids.fasterpam(diss, 5, max_iter=100, init='random', random_state=None, n_cpu=-1)

KMedoidsResult(loss=896.0, labels=[2 0 4 0 3 0 1 2 0 2 0 3 0 3 3 3 0 2 2 0 2 2 0 0 2 1 2 0 3 3 3 0 1 1 1 0 0
 2 0 0 1 3 0 2 0 2 0 0 4 0 1 2 2 4 2 0 4 0 2 2 2 2 1 2 2 0 2 1 1 0 0 1 2 2
 0 2 3 3 2 4 2 0 3 2 3 2 2 2 0 1 0 2 1 1 0 1 0 1 0 3 1 1 1 0 2 3 2 0 1 2 2
 3 0 2 4 0 4 1 2 2 0 2 2 3 4 2 1 2 0 0 2 2 4 1 2 1 4 2 2 3 2 1 2 4 0 2 3 0
 1 2 2 3 3 2 2 3 2 0 3 0 2 0 1 2 4 2 0 1 2 0 1 0 2 0 3 2 2 2 2 2 0 0 1 0 2
 4 0 2 3 0 2 0 0 3 2 3 1 0 2], medoids=[ 16  71 137 193 114], n_iter=2, n_swaps=19)

In [26]:
diss.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'