* Memanggil Dataset

In [1]:
import pandas as pd
from kmodes.kmodes import KModes
import numpy as np

In [2]:
DATA_TA=pd.read_csv("Dataclean.csv")

In [3]:
DATA_TA

Kabupaten/Kota Nama Kepala Rumah Tangga   X1  X2  X3  X4  X5  X6  \
0        KOTA BANDA ACEH             WAHYU HIDAYAT   1   1   1   2   1   1   
1        KOTA BANDA ACEH                    MUCHRI   2   1   1   6   1   2   
2        KOTA BANDA ACEH                 USMAN ALI   1   1   1   6   1   1   
3        KOTA BANDA ACEH                    EFENDI   1   1   1   6   1   1   
4        KOTA BANDA ACEH               FARIDAHWATI   1   2   4   6   1   1   
...                  ...                       ...  ..  ..  ..  ..  ..  ..   
60744  KOTA SUBULUSSALAM             DANI SAPUTERA   1   3   4   6   1   2   
60745  KOTA SUBULUSSALAM                  SULASTRI   1   1   1   6   3   2   
60746  KOTA SUBULUSSALAM                     KARDA   1   1   1   6   3   2   
60747  KOTA SUBULUSSALAM                 SUWARSONO   1   1   1   6   1   1   
60748  KOTA SUBULUSSALAM                   PURNOMO   1   5   4   6   3   2   

       X7  X8  ...  X26  X27  X28  X29  X30  X31  X32  X33  X34  Y  
0       6   1  ...    1    2    2    2    2    2    1    2    2  5  
1       6   2  ...    1    2    2    2    2    2    1    2    2  2  
2       6   1  ...    1    2    2    2    2    2    1    2    1  5  
3       6   1  ...    1    2    2    2    2    2    1    2    1  5  
4       6   1  ...    2    2    2    2    2    2    2    2    2  5  
...    ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  
60744   6   2  ...    2    2    2    2    2    2    2    2    2  3  
60745   6   2  ...    2    2    2    2    2    2    1    2    1  5  
60746   6   2  ...    2    2    2    2    2    2    1    2    2  3  
60747   6   1  ...    1    1    2    2    2    2    1    2    1  5  
60748   6   2  ...    2    2    2    2    2    2    1    2    2  3  

[60749 rows x 37 columns]

* Mendeteksi data duplikat

In [4]:
DATA_TA_CLEAN= DATA_TA.drop_duplicates()

In [5]:
DATA_TA_CLEAN.describe()

X1            X2            X3            X4            X5  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.492542      1.471503      1.990682      5.774183      2.364662   
std        0.669497      0.849359      1.332241      1.717152      1.159472   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      6.000000      1.000000   
50%        1.000000      1.000000      1.000000      6.000000      3.000000   
75%        2.000000      2.000000      4.000000      6.000000      3.000000   
max        3.000000      5.000000      4.000000     10.000000      7.000000   

                 X6            X7            X8            X9           X10  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.760273      6.064204      1.751366      1.894475      4.033748   
std        0.426921      0.830969      0.432224      0.761282      2.340832   
min        1.000000      1.000000      1.000000      0.000000      1.000000   
25%        2.000000      6.000000      2.000000      1.000000      2.000000   
50%        2.000000      6.000000      2.000000      2.000000      3.000000   
75%        2.000000      6.000000      2.000000      2.000000      6.000000   
max        2.000000     10.000000      2.000000      9.000000     12.000000   

       ...           X26           X27           X28           X29  \
count  ...  60744.000000  60744.000000  60744.000000  60744.000000   
mean   ...      1.375280      1.985200      1.990106      1.993003   
std    ...      0.484199      0.120752      0.098976      0.083353   
min    ...      1.000000      1.000000      1.000000      1.000000   
25%    ...      1.000000      2.000000      2.000000      2.000000   
50%    ...      1.000000      2.000000      2.000000      2.000000   
75%    ...      2.000000      2.000000      2.000000      2.000000   
max    ...      2.000000      2.000000      2.000000      2.000000   

                X30           X31           X32           X33           X34  \
count  60744.000000  60744.000000  60744.000000  60744.000000  60744.000000   
mean       1.989448      1.999243      1.324542      1.983636      1.628605   
std        0.102183      0.027508      0.468207      0.126871      0.483182   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        2.000000      2.000000      1.000000      2.000000      1.000000   
50%        2.000000      2.000000      1.000000      2.000000      2.000000   
75%        2.000000      2.000000      2.000000      2.000000      2.000000   
max        2.000000      2.000000      2.000000      2.000000      2.000000   

                  Y  
count  60744.000000  
mean       3.670206  
std        1.254295  
min        1.000000  
25%        3.000000  
50%        4.000000  
75%        5.000000  
max        5.000000  

[8 rows x 35 columns]

In [7]:
DATA_TA_CLEAN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60744 entries, 0 to 60748
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Kabupaten/Kota             60744 non-null  object
 1   Nama Kepala Rumah Tangga   60744 non-null  object
 2   X1                         60744 non-null  int64 
 3   X2                         60744 non-null  int64 
 4   X3                         60744 non-null  int64 
 5   X4                         60744 non-null  int64 
 6   X5                         60744 non-null  int64 
 7   X6                         60744 non-null  int64 
 8   X7                         60744 non-null  int64 
 9   X8                         60744 non-null  int64 
 10  X9                         60744 non-null  int64 
 11  X10                        60744 non-null  int64 
 12  X11                        60744 non-null  int64 
 13  X12                        60744 non-null  int64 
 14  X13        

In [8]:
MYDATA=DATA_TA_CLEAN

In [9]:
DATAKU=DATA_TA_CLEAN[["X1","X15","X10","X13","X4","X14","X19","X11","X16","X5","X26"]]
DATAKU

X1  X15  X10  X13  X4  X14  X19  X11  X16  X5  X26
0       1    1    2    4   2    3    1    1    1   1    1
1       2    1    2    4   6    3    1    1    1   1    1
2       1    1    2    4   6    9    2    1    1   1    1
3       1    1    2    4   6    2    2    1    1   1    1
4       1    1    3    4   6    3    2    2    1   1    2
...    ..  ...  ...  ...  ..  ...  ...  ...  ...  ..  ...
60744   1    1    7    6   6    8    2    3    3   1    2
60745   1    1    7    4   6    3    2    3    1   3    2
60746   1    1    7    4   6    8    1    3    3   3    2
60747   1    1    6    4   6    3    1    3    1   1    1
60748   1    1    7    5   6    8    2    3    1   3    2

[60744 rows x 11 columns]

In [13]:
#Cluster menggunakan KMODES

In [11]:
km=KModes(n_clusters=5, max_iter=1000, init='random')
clusters=km.fit_predict(DATAKU)
clusters

array([0, 0, 0, ..., 3, 0, 3], dtype=uint16)

In [12]:
print(km.cluster_centroids_)

[[1 1 2 4 6 3 1 1 1 1 1]
 [1 1 2 5 6 3 2 1 1 3 2]
 [2 1 6 5 6 3 2 3 1 3 1]
 [1 4 7 5 6 8 2 3 4 3 2]
 [2 1 2 5 6 3 1 1 1 3 1]]


In [13]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [14]:
MYDATA["cluster_kmodes"]=cluster_dict
MYDATA

C:\Users\Alharidt\AppData\Local\Temp\ipykernel_10372\1961625719.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MYDATA["cluster_kmodes"]=cluster_dict


Kabupaten/Kota Nama Kepala Rumah Tangga   X1  X2  X3  X4  X5  X6  \
0        KOTA BANDA ACEH             WAHYU HIDAYAT   1   1   1   2   1   1   
1        KOTA BANDA ACEH                    MUCHRI   2   1   1   6   1   2   
2        KOTA BANDA ACEH                 USMAN ALI   1   1   1   6   1   1   
3        KOTA BANDA ACEH                    EFENDI   1   1   1   6   1   1   
4        KOTA BANDA ACEH               FARIDAHWATI   1   2   4   6   1   1   
...                  ...                       ...  ..  ..  ..  ..  ..  ..   
60744  KOTA SUBULUSSALAM             DANI SAPUTERA   1   3   4   6   1   2   
60745  KOTA SUBULUSSALAM                  SULASTRI   1   1   1   6   3   2   
60746  KOTA SUBULUSSALAM                     KARDA   1   1   1   6   3   2   
60747  KOTA SUBULUSSALAM                 SUWARSONO   1   1   1   6   1   1   
60748  KOTA SUBULUSSALAM                   PURNOMO   1   5   4   6   3   2   

       X7  X8  ...  X27  X28  X29  X30  X31  X32  X33  X34  Y  cluster_kmodes  
0       6   1  ...    2    2    2    2    2    1    2    2  5               0  
1       6   2  ...    2    2    2    2    2    1    2    2  2               0  
2       6   1  ...    2    2    2    2    2    1    2    1  5               0  
3       6   1  ...    2    2    2    2    2    1    2    1  5               0  
4       6   1  ...    2    2    2    2    2    2    2    2  5               0  
...    ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ... ..             ...  
60744   6   2  ...    2    2    2    2    2    2    2    2  3               3  
60745   6   2  ...    2    2    2    2    2    1    2    1  5               1  
60746   6   2  ...    2    2    2    2    2    1    2    2  3               3  
60747   6   1  ...    1    2    2    2    2    1    2    1  5               0  
60748   6   2  ...    2    2    2    2    2    1    2    2  3               3  

[60744 rows x 38 columns]

In [18]:
MYDATA.to_excel('MYDATA.xlsx', index=False)